name: Deploy Bot Translator

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu:22.04

    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: your-server-ip
        username: your-username
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/home/np_bot/docker
          git pull origin main
          docker-compose down
          docker-compose up -d
